# -*- coding:utf-8 -*-
# @author: luning
# @create_on: Sep 26, 2018
# @file_name: constant.py

# 常用变量封装
constant = {
    'URL': {
        'WECHAT': 'https://weixin.sogou.com/weixin'
    },
    'PAGE_NUM': 500,
    'LIST_TYPE': 0,
    'ARTICLE_TYPE': 1,
    'COOKIE_LIST': [
        {
            "domain": ".sogou.com",
            "expirationDate": 1540289048.176131,
            "hostOnly": False,
            "httpOnly": False,
            "name": "ad",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "Ulllllllll2bPiJxlllllVmXBSklllll11NtxZllll9lllllVCxlw@@@@@@@@@@@",
            "id": 1
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1551947250.318235,
            "hostOnly": False,
            "httpOnly": False,
            "name": "CXID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "BA5B12C2C4904C276D6564FC7B839299",
            "id": 2
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1548831360.344055,
            "hostOnly": False,
            "httpOnly": False,
            "name": "IPLOC",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "CN1100",
            "id": 3
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 2147385600,
            "hostOnly": False,
            "httpOnly": False,
            "name": "pgv_pvi",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "9994099712",
            "id": 4
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1539219561.891646,
            "hostOnly": False,
            "httpOnly": False,
            "name": "ppinf",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "5|1538009961|1539219561|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZTozMzolRTklQjIlODElRTUlQUUlODElRTIlOTklQTFUaGFua3N8Y3J0OjEwOjE1MzgwMDk5NjF8cmVmbmljazozMzolRTklQjIlODElRTUlQUUlODElRTIlOTklQTFUaGFua3N8dXNlcmlkOjQ0Om85dDJsdUI3RjR6MG9oem5KZWVDbEhTOF9KQU1Ad2VpeGluLnNvaHUuY29tfA",
            "id": 5
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1539219561.89186,
            "hostOnly": False,
            "httpOnly": False,
            "name": "pprdig",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "MdZT_68leELtprNAyS_AkjkEiL9XsGKn_G6lq4ANzYLJQy44h9xckSR_J4adXWOC-QoU4JZLM6Stx1Dz1gqn7tFu-gNd1avlH4iXMoS-yUkvh2Kp99YmS5Dsv1TuTOyFhBQVkmuFDbydMvhB2ww11RQxc_MUi7_uvvpi524gur0",
            "id": 6
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1595289600,
            "hostOnly": False,
            "httpOnly": False,
            "name": "sct",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "9",
            "id": 7
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1539219561.892046,
            "hostOnly": False,
            "httpOnly": False,
            "name": "sgid",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "31-37228897-AVusK2l25tAVWAwupJib53yY",
            "id": 8
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1569546985,
            "hostOnly": False,
            "httpOnly": False,
            "name": "SNUID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "DCFD14A7DBDFAD0BCDBCB399DB87FB70",
            "id": 9
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 2547035861,
            "hostOnly": False,
            "httpOnly": False,
            "name": "SUID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "077AFF726119940A000000005A7017B4",
            "id": 10
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1538591324.955876,
            "hostOnly": False,
            "httpOnly": False,
            "name": "SUIR",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "7C263DA97B7E0CB9CD9AEF7E7B948C85",
            "id": 11
        },
        {
            "domain": ".sogou.com",
            "expirationDate": 1785283200,
            "hostOnly": False,
            "httpOnly": False,
            "name": "SUV",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "1517295360424207",
            "id": 12
        },
        {
            "domain": "weixin.sogou.com",
            "expirationDate": 1540549542.237447,
            "hostOnly": True,
            "httpOnly": False,
            "name": "ABTEST",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "0|1537957542|v1",
            "id": 13
        },
        {
            "domain": "weixin.sogou.com",
            "hostOnly": True,
            "httpOnly": False,
            "name": "JSESSIONID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": True,
            "storeId": "0",
            "value": "aaaW1yuQsDAWo-8O18Bvw",
            "id": 14
        },
        {
            "domain": "weixin.sogou.com",
            "hostOnly": True,
            "httpOnly": False,
            "name": "PHPSESSID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": True,
            "storeId": "0",
            "value": "1r1q47t2568sai2h6k6sosk0f4",
            "id": 15
        },
        {
            "domain": "weixin.sogou.com",
            "hostOnly": True,
            "httpOnly": True,
            "name": "ppmdig",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": True,
            "storeId": "0",
            "value": "1538009961000000e8b0efbae8f438a8e19044cda6418a2c",
            "id": 16
        },
        {
            "domain": "weixin.sogou.com",
            "expirationDate": 1546597543,
            "hostOnly": True,
            "httpOnly": False,
            "name": "weixinIndexVisited",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "1",
            "id": 17
        }
    ]
}